apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: home-lab
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 4.8.0
    helm:
      values: |
        loki:
          auth_enabled: false

        storage:
            boltdb_shipper:
              active_index_directory: /loki/index
              cache_location: /loki/index_cache
              resync_interval: 5s
              shared_store: s3
          bucketNames:
            chunks: chunks
            ruler: ruler
            admin: admin
          type: s3
          s3: # minio connect configuration
            s3: http://minio:minio123@min-io.mini-io:.:9000/loki
            bucketnames: chunks
            access_key_id: minio
            secret_access_key: minio123
            s3forcepathstyle: true
            insecure: true
            region: null

        backend:
          replicas: 2
          persistence:
            size: 10Gi
            storageClass: nfs-client

        # Configuration for the write
        write:
          # Number of replicas for the write
          replicas: 2
          persistence:
            # -- Size of persistent disk
            size: 10Gi
            # -- Storage class to be used.
            storageClass: nfs-client

        # Configuration for the read
        read:
          # Number of replicas for the read
          replicas: 2
          persistence:
            # -- Size of persistent disk
            size: 10Gi
            # -- Storage class to be used.
            storageClass: nfs-client

        # Configuration for the gateway
        gateway:
          # -- Specifies whether the gateway should be enabled
          enabled: true
          # -- Number of replicas for the gateway
          replicas: 1

        # Disable mino installation
        minio:
          enabled: false

        # Disable self-monitoring
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
            lokiCanary:
                enabled: false

        # Disable helm-test
        test:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: loki