apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: home-lab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: loki
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.2.0
    helm:
      values: |
        loki:
          auth_enabled: false

          ingester:
            chunk_idle_period: 1h
            chunk_target_size: 1536000
            max_chunk_age: 1h

          schemaConfig:
            configs:
            - from: 2024-04-01
              store: boltdb-shipper
              object_store: s3
              store: tsdb
              schema: v13
              index:
                prefix: loki_index
                period: 24h

          storage_config:
            boltdb_shipper:
              active_index_directory: /var/loki/index
              cache_location: /var/loki/index_cache
              resync_interval: 5s
              cache_ttl: 1h
          
          storage:
            bucketNames:
              chunks: loki
              ruler: loki
              admin: loki
            type: s3
            s3: # minio connect configuration
              s3: null
              endpoint: http://min-io.min-io:9000
              bucketNames: loki
              accessKeyId: ${MINIO_ACCESS_KEY_ID}
              secretAccessKey: ${MINIO_SECRET_ACCESS_KEY}
              s3ForcePathStyle: true
              insecure: true
              region: null

        backend:
          replicas: 2
          persistence:
            size: 10Gi
            storageClass: nfs-client

        # Configuration for the write
        write:
          # Number of replicas for the write
          replicas: 2
          persistence:
            # -- Size of persistent disk
            size: 10Gi
            # -- Storage class to be used.
            storageClass: nfs-client

          extraArgs:
            - '-config.expand-env=true'
          extraEnv:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: loki-minio-creds
                  key: MINIO_ACCESS_KEY_ID
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: loki-minio-creds
                  key: MINIO_SECRET_ACCESS_KEY
        
        # Configuration for the read
        read:
          # Number of replicas for the read
          replicas: 2
          persistence:
            # -- Size of persistent disk
            size: 10Gi
            # -- Storage class to be used.
            storageClass: nfs-client

          extraArgs:
            - '-config.expand-env=true'
          extraEnv:
            - name: MINIO_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-minio-creds
                  key: MINIO_ACCESS_KEY_ID
            - name: MINIO_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-minio-creds
                  key: MINIO_SECRET_ACCESS_KEY

        # Configuration for the gateway
        gateway:
          # -- Specifies whether the gateway should be enabled
          enabled: true
          # -- Number of replicas for the gateway
          replicas: 1

        # Disable mino installation
        minio:
          enabled: false

        # Disable self-monitoring
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
            lokiCanary:
                enabled: false

        # Disable helm-test
        test:
          enabled: false