apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: home-lab
  source:
    chart: homelab-loki
    repoURL: https://github.com/thedanfields/homelab-cluster.git
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: loki