loki:
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    type: s3
    s3: # minio connect configuration
      endpoint: min-io.mini-io.svc.cluster.local.:9000
      bucketnames: chunks
      access_key_id: minio
      secret_access_key: minio123
      s3forcepathstyle: true
      insecure: true

# Configuration for the write
write:
  # Number of replicas for the write
  replicas: 2
  persistence:
    # -- Size of persistent disk
    size: 10Gi
    # -- Storage class to be used.
    storageClass: nfs-client

# Configuration for the read
read:
  # Number of replicas for the read
  replicas: 2
  persistence:
    # -- Size of persistent disk
    size: 10Gi
    # -- Storage class to be used.
    storageClass: nfs-client

# Configuration for the gateway
gateway:
  # -- Specifies whether the gateway should be enabled
  enabled: true
  # -- Number of replicas for the gateway
  replicas: 1

# Disable mino installation
minio:
  enabled: false

# Disable self-monitoring
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
    lokiCanary:
        enabled: false

# Disable helm-test
test:
  enabled: false