storage:
  bucketNames:
    chunks: chunks
    ruler: ruler
    admin: admin
  type: s3
  s3: # minio connect configuration
    endpoint: min-io.mini-io.svc.cluster.local.:9000
    bucketnames: chunks
    access_key_id: minio
    secret_access_key: minio123
    s3forcepathstyle: true
    insecure: true