apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: home-lab
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: v58.2.0  
    helm:
      skipCrds: true 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus