apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: home-lab
spec:
  project: home-lab
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.7.1
    chart: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus