apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-2
  namespace: argocd
spec:
  project: home-lab
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 4.8.0
    helm:
      releaseName: loki
      valueFiles:
      - values.yaml
  destination:
    server: "https://kubernetes.default.svc"