apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd 
spec:
  project: home-lab
  source:
    chart: envoy-gateway
    repoURL: docker.io/envoyproxy/envoy-gateway
    targetRevision: v1.0.1

  destination:
    server: "https://kubernetes.default.svc"
    namespace: envoy-gateway