apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd 
spec:
  project: home-lab
  source:
    chart: gateway-helm
    repoURL: oci://docker.io/envoyproxy/gateway-helm
    targetRevision: v1.0.1

  destination:
    server: "https://kubernetes.default.svc"
    namespace: envoy-gateway