apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: home-lab
spec:
  selector:
    app.kubernetes.io/name: homelab-proxy
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  - name: https
    port: 443