apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs
  namespace: home-lab
  labels:
    volume: logs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  nfs:
    server: lenny.cluster
    path: /media/storage/nfs_share/home_lab_logs