apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  namespace: storage
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: lenny.cluster
            - name: NFS_PATH
              value: /media/storage/nfs_share/cluster
      volumes:
        - name: nfs-client-root
          nfs:
            server: lenny.cluster
            path: /media/storage/nfs_share/cluster