kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
  namespace: storage-test
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-test
  namespace: storage-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-test
      version: v1
  template:
    metadata:
      labels:
        app: storage-test
        version: v1
    spec:
      containers:
        - name: test-storage
          image: gcr.io/google_containers/busybox:1.24
          resources:
            limits:
              cpu: 200m
              memory: 170Mi
            requests:
              cpu: 100m
              memory: 70Mi
          command:
            - "/bin/sh"
          args:
            - "-c"
            - "touch /mnt/SUCCESS && exit 0 || exit 1"
          volumeMounts:
            - name: nfs-vol
              mountPath: "/mnt"
      volumes:
        - name: nfs-vol
          persistentVolumeClaim:
            claimName: test-pvc