apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: home-lab
data:
  HomeLabFile: |
    $TTL    3600
    $ORIGIN home.lab.
    @                    IN  SOA   ns.home.lab. contact.home.lab. (
                                               2023121301 ; serial
                                               1d ; refresh
                                               2h ; retry
                                               4w ; expire
                                               1h ; nxdomain ttl
                                              )
                         IN  NS  ns.home.lab.
    @                    IN  A   192.168.186.203
    *                    IN  A   192.168.186.203
  Corefile: |
    home.lab:53 {
      file /etc/coredns/db.home.lab
      log
      errors
      health :8080
      ready :8181
      reload
    }

    .:53 {
      forward . 192.168.186.3
      log
      errors
      health :8080
      ready :8181
      reload
      cache
    }