apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: home-lab
data:
  Corefile: |
    .:53 {
      forward . 8.8.8.8 9.9.9.9
      log
      errors
      health :8080
      ready :8181
      reload
    }