apiVersion: v1
kind: Service
metadata:
  name: dns-service
  namespace: home-lab
spec:
  selector:
    app.kubernetes.io/name: homelab-dns
  type: LoadBalancer
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: metrics
    port: 9153
    protocol: TCP