apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: home-lab
  namespace: envoy-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: home-lab
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Passthrough
