apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: home-lab
data:
  HomeLabFile: |
    $TTL    3600
    $ORIGIN lcl-lab.com.
    @                    IN  SOA   ns.lcl-lab.com. contact.lcl-lab.com. (
                                               2023121301 ; serial
                                               1d ; refresh
                                               2h ; retry
                                               4w ; expire
                                               1h ; nxdomain ttl
                                              )
                         IN  NS  ns.lcl-lab.com.
    @                    IN  A   192.168.186.205
    *                    IN  A   192.168.186.205
  Corefile: |
    lcl-lab.com:53 {
      file /etc/coredns/db.home.lab
      log
      errors
      health :8080
      ready :8181
      reload
    }

    .:53 {
      forward . 208.67.222.123
      log
      errors
      health :8080
      ready :8181
      reload
      cache
    }