apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argo-cd-route
spec:
  parentRefs:
    - name: home-lab
  hostnames:
    - "argo.home.lab"
  rules:
    - backendRefs:
        - name: argocd-server
          namespace: argocd
          port: 443