apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: home-lab
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.15.5
    helm:
      values: |
        config:
          clients:
            - url: http://loki-gateway.loki:80/loki/api/v1/push
            
 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: promtail