apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: home-lab
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.11.0
    helm:
      values: |
        config:
          clients:
            - url: https://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
            
 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: promtail