apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: prometheus-grafana
spec:
  parentRefs:
    - name: home-lab
  hostnames:
    - "logging.home.lab"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: prometheus-grafana
          namespace: prometheus
          port: 80
          weight: 1