apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: min-io
  name: min-io
  labels:
    app: min-io
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      volume: min-io